version: '3.7'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./pythonfavrepo:/docker-entrypoint-initdb.d/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "pythonfavrepo"
      MYSQL_USER: "pythonfavrepo"
      MYSQL_PASSWORD: "pythonfavrepo"
  pythonfavrepo:
    build:
      dockerfile: ./devops/Dockerfile
      context: .
      target: app
    restart: always
    ports:
      - 8000:8000
    command: wait-for-it --service db:3306 --timeout 30 -- flask run -h 0.0.0.0 -p 8000
    environment:
      DB_NAME: "pythonfavrepo"
      DB_USER: "pythonfavrepo"
      DB_PASS: "pythonfavrepo"
      DB_HOST: "db"
      FLASK_APP: "pythonfavrepo"
      FLASK_ENV: "development"
    links:
      - db